### ISSUE TITLE
One user cant' play anymore : In the backend she is at the round 14

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/jquest#78]
![capture d ecran 2016-09-09 a 15 05 27](https://cloud.githubusercontent.com/assets/2103603/18387780/f350a6b8-769e-11e6-8285-f96fbd19283e.png)

User here : http://www.jquestapp.com/admin/users/100

What happened?
* The user arrives at level 7, but there is no representatives in our database that matche the criteria of her level 7
* I add representatives that match in the DB
* She receives 6 assignements but she still can't play
----> We see in the backend that she is level 7 round 14

**Comment by annelisebouyer** [comment]
I have no idea why but it happened again : http://www.jquestapp.com/admin/users/100
ping @pirhoo

**Comment by pirhoo** [comment]
I have no clue but in the meantime you can set the right round here:
http://www.jquestapp.com/admin/users/100/points/116/edit

**Comment by annelisebouyer** [comment]
Done ! Thanks
