### ISSUE TITLE
Leaderboard: User's points is inaccurate

### ISSUE THREAD

**Issue by n-kb** [jplusplus/jquest#83]
From screenshot: it doesn't seem to be a cache issue (i.e other users' points are accurate):

![screenshot from 2016-10-03 09 17 13](https://cloud.githubusercontent.com/assets/864677/19029884/49f21b60-894a-11e6-947b-bcc4aaf6a785.png)

**Comment by pirhoo** [comment]
There is cache for each user so it doesn't mean it's not a cache issue.
