### ISSUE TITLE
Invite email: Display the status of the account in the overview of users

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/jquest#93]
When we are here http://www.jquestapp.com/admin/users it would be great to have a column 'Confirmed at' that displays the content of this field:
![capture d ecran 2016-11-28 a 14 53 39](https://cloud.githubusercontent.com/assets/2103603/20670751/afa65096-b57a-11e6-9030-e8e33b742e75.png)

So that I can have an overview of the users that have confirmed their account or not (it the field is empty, they didn't).
Thanks!

**Comment by pirhoo** [comment]
![capture du 2016-11-30 18-47-29](https://cloud.githubusercontent.com/assets/471176/20789264/ec3c07b8-b7b3-11e6-94b8-f7db7dd013db.png)
![capture du 2016-11-30 18-47-10](https://cloud.githubusercontent.com/assets/471176/20789265/ec3fd7a8-b7b3-11e6-8145-ad44072f6ac7.png)
