### ISSUE TITLE
Invite emails: Prevent users to receive multiple emails invite

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/jquest#94]
When the connection is lagging, and we invite users, they receive the email invite many times (because we click many times). It would be great to have a one hour delay between 2 invites received. So make it impossible to resend an invite email if the previous one has less than 1 hour.
Is it possible ?

**Comment by pirhoo** [comment]
I added a 5 minutes delay for each user and a small "Unboarding" panel:
![capture du 2016-12-01 11-58-31](https://cloud.githubusercontent.com/assets/471176/20791495/9d954980-b7bd-11e6-821e-7bb25cac3543.png)
