### ISSUE TITLE
Invite emails: Expiration of the invites

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/jquest#95]
Currently the users reported that the invites expire but we don't know when.
Would it be possible to:
- configure the invite so that they never expire
or
- display a field in a user overview: invite expired (yes/no)

**Comment by pirhoo** [comment]
Everything I tested  tends to confirm that there is no expiration delay for the invitation. The only reason that can invalidate an invitation token is if someone sent another one. I suppose its a duplicate of #94 then.
